# Generated by Django 4.2.7 on 2023-12-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0003_corretor_remove_imovel_inquilino_contrato_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='idade',
            field=models.IntegerField(null=True),
        ),
    ]
